// Generated by CoffeeScript 2.7.0
(function() {
  // coffee -cw scripts/main.coffee
  var button1, button2, button3;

  button1 = document.getElementById("dosomthing");

  button1.addEventListener("click", function() {
    if (Math.random() < 0.5) {
      return window.open("https://en.wikipedia.org/wiki/Productivity", "_blank");
    } else {
      return alert("No productivity today. Try again.");
    }
  });

  button2 = document.getElementById("playmtt");

  button2.addEventListener("click", function() {
    return window.open("game.html", "_blank");
  });

  button3 = document.getElementById("startgame");

  button3.addEventListener("click", function() {
    return window.open("game2.html", "_blank");
  });

}).call(this);
